version: "3.8"

services:
  nginx:
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-production.conf:/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: portfolio_certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - static:/data/letsencrypt
    command: --nginx
    # command: certonly --webroot -w /data/letsencrypt --test-cert  --force-renewal --email ${SSL_EMAIL} -d giannisbratias.xyz --agree-tos

  django:
    restart: always
    command: /runserver.sh