name: 0 - Run everything

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  test_django:
    uses: ./.github/workflows/test-django.yaml
  build_container:
    needs: test_django
    uses: ./.github/workflows/container.yaml